[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
    "pants.backend.experimental.go",
    "pants.backend.experimental.codegen.protobuf.go"
]

[anonymous-telemetry]
enabled = false
repo_id = "BFC7EF33-D529-4D20-8227-6951953E5729"

[golang]
expected_version = "1.18"